root: Skip 'command' check.
This command should be checked for, but I don't remember how to make
'bash' do the check without using another binary!

diff --git a/root/init b/root/init
--- a/root/init
+++ b/root/init
@@ -166,10 +166,12 @@ switch() {
 # Validate the system. This function is not comprehensive.
 system_validate() {
 	# Check for 'mkpasswd'
-	if ! command -v mkpasswd > /dev/null; then
-		echo "Unable to find 'mkpasswd' utility."
-		exit 1
-	fi
+	# Apparently 'command' is a binary that would need to be inserted into
+	# the 'initramfs' as well...
+	#if ! command -v mkpasswd > /dev/null; then
+	#	echo "Unable to find 'mkpasswd' utility."
+	#	exit 1
+	#fi
 }
 
 # The main function (duh).
